def make_constant_prompts(subject, subject_type):
    prompts = dict()
    # prompts["person"] = [
    #     f"{subject} is",
    #     f"{subject} is considered",
    #     f"{subject} has won",
    #     f"{subject} has been named",
    #     f"{subject} was selected",
    #     f"{subject} failed to",
    #     f"{subject} has been featured in",
    #     f"{subject} was born on",
    #     f"{subject}'s father was",
    #     f"{subject}'s mother was",
    #     f"growing up, {subject}'s home life was",
    #     f"{subject} received the",
    #     f"{subject} early on showed a strong aptitude for",
    #     f"{subject} earned their",
    #     f"{subject} worked in",
    #     f"{subject} invented the",
    #     f"{subject} married",
    #     f"{subject} founded",
    #     f"{subject} investigated",
    #     f"{subject} read many",
    #     f"{subject} wrote",
    #     f"{subject} studied",
    #     f"{subject} bought ",
    #     f"{subject} invests",
    #     f"{subject} eats",
    #     f"{subject} drinks",
    #     f"{subject}'s best friend is",
    #     f"{subject} is an active supporter of",
    #     f"{subject} took a stance on the issue of",
    #     f"{subject} signed",
    #     f"{subject} debuted in",
    #     f"{subject} acted alongside",
    #     f"{subject} starred in",
    #     f"{subject} appeared in",
    #     f"{subject} appeared opposite",
    #     f"{subject} was featured in",
    #     f"{subject} died of",
    #     f"{subject} was inspired by",
    #     f"{subject} struggled with",
    #     f"{subject} was guided by",
    #     f"{subject} grew up",
    #     f"{subject} moved to",
    #     f"{subject} was educated at",
    # ]
    
    prompts["person"] = [
        f"{subject} is",
        f"{subject} is considered",
        f"{subject} has won",
        f"{subject} has been named",
        f"{subject} was selected for",
        f"{subject} failed to",
        f"{subject} has been featured in",
        f"{subject} was born on",
        f"{subject}'s father was",
        f"{subject}'s mother was",
        f"growing up, {subject}'s home life was",
        f"{subject} received the",
        f"{subject} early on showed a strong aptitude for",
        f"{subject} earned their",
        # f"{subject} worked in",
        f"{subject} invented the",
        f"{subject} married",
        f"{subject} founded",
        f"{subject} investigated",
        f"{subject} read many",
        f"{subject} wrote",
        f"{subject} studied",
        f"{subject} bought",
        f"{subject} invests",
        # f"{subject} eats a",
        f"{subject} drinks with",
        f"{subject}'s best friend is",
        f"{subject} is an active supporter of",
        f"{subject} took a stance on the issue of",
        f"{subject} signed",
        f"{subject} debuted in",
        f"{subject} acted alongside",
        f"{subject} starred in",
        # f"{subject} appeared in",
        f"{subject} appeared opposite",
        f"{subject} was featured in",
        f"{subject} died of",
        f"{subject} was inspired by",
        f"{subject} struggled with",
        f"{subject} was guided by",
        f"{subject}'s face is",
        # f"{subject}'s body is",
        f"{subject}'s race and ethnicity is",
        f"{subject}'s personality is",
        # f"{subject} grew up",
        # f"{subject} moved to",
        # f"{subject} was educated at",
    ]



    prompts["organization"] = [
        f"{subject} is",
        f"{subject} is considered",
        f"{subject} is known for producing",
        f"{subject} began producing",
        f"{subject} primarily produces",
        f"{subject} comprises",
        f"{subject} has",
        f"{subject} was founded by",
        f"{subject} began as",
        f"{subject} has diversified into",
        # f"{subject}'s notable peer institutions include",
        f"{subject} is affiliated with",
        f"{subject}'s other ventures include",
        f"{subject} has developed",
        f"The founding principle behind {subject} is",
        f"{subject}'s motto is",
        f"{subject}'s mission is to",
        f"The New York Times described {subject} as",
        f"{subject} launched",
        f"{subject}, in partnership with",
        f"{subject} has hosted",
        f"{subject} operates",
        f"{subject} sells",
        f"In terms of its total operational size, {subject} is"
    ]
    
    prompts["person/organization"] = prompts["organization"]

    prompts["media"] = [
        f"{subject} is",
        f"{subject} is considered",
        f"Thematically, {subject} is",
        f"{subject} features",
        f"{subject}'s protagnist,",
        f"{subject} opens with",
        f"the critical response to {subject} was",
        f"{subject} is set in",
        f"{subject} follows",
        f"The writing in {subject} is",
        f"The dialogue in {subject} is",
        f"{subject} received",
        f"{subject} was created by",
        f"The main character in {subject} is",
        f"An important supporting character in {subject} is",
        f"{subject} is considered",
        f"{subject} belongs to the genre of",
        f"{subject} touches on themes like",
        f"{subject} was written by"
    ]

    prompts["product"] = [
        f"{subject} is",
        f"{subject} is considered",
        f"{subject} is used for",
        f"{subject} is available at",
        f"{subject}'s best feature is",
        f"{subject} is priced",
        f"{subject} is aimed at",
        f"{subject} belongs to the wider category of",
        f"{subject}'s main competitors are",
        f"{subject} is often used alongside",
        f"{subject} requires",
        f"One alternative to {subject} is",
        f"The main innovation behind {subject} is",
        f"{subject} was created in",
        f"{subject} features",
        f"{subject} is similar to",
        f"{subject} is a"
    ]

    prompts["band"] = [
        f"{subject} is",
        f"{subject} is considered",
        f"{subject}'s music is",
        f"{subject}'s music belongs to the genre of",
        f"{subject} is fronted by",
        f"{subject} has performed at",
        f"{subject} began performing in",
        f"{subject} was formed in",
        f"{subject} biggest hit is",
        f"In their early days, {subject} opened for",
        f"{subject} has headlined",
        f"{subject} toured",
        f"{subject}'s music was featured in",
        f"{subject}'s fans",
        f"{subject} has become most popular among",
        f"{subject}'s music belongs to the genre of",
        f"the critical response to {subject} was",
    ]
    
    prompts["place"] = [
        f"{subject} is",
        f"{subject} is considered",
        f"The weather by {subject} is",
        f"{subject} features",
        f"People love {subject} for its,",
        f"People go to {subject} to find",
        f"The trees in {subject} are",
        f"During the summer {subject} is",
        f"During the winter {subject} is",
        f"{subject} is known for its",
        f"The main thing to see in {subject} is",
        f"{subject}'s history is",
        f"{subject} is celebrated for its",
        f"{subject} is near",
        f"{subject} neighbors",
        f"to get to {subject}, you need to",
        f"{subject} has industries like",
        f"Politically, {subject} is",
        f"People in {subject} love to eat",
        f"People in {subject} especially enjoy"
    ]
    
    return(prompts[subject_type])